version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    branches:
      ignore: gh-pages
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - store_artifacts:
                path: coverage
            - run:
                name: Upload CodeCov.io Data
                command: bash <(curl -s https://codecov.io/bash) -f coverage/*.json
                when: always

workflows:
    build-and-test:
      jobs:
        - build-and-test
