// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cat': string;
  'cattitle': string;
  'date': string;
  'desc': string;
  'item': string;
  'items': string;
  'itemtitle': string;
  'links': string;
  'projectlist': string;
  'stack': string;
  'svgwrapper': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
