// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'call': string;
  'copy': string;
  'fronticon': string;
  'infoline': string;
  'infos': string;
  'name': string;
  'profession': string;
  'social': string;
  'svgwrapper': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
