// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'langdesc': string;
  'langname': string;
  'ul': string;
}
export const cssExports: CssExports;
export default cssExports;
